spring.application.name=tfg
# 1. Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:15432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234Tfg
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
